### ISSUE TITLE
Create an interactive chart for ECG (beginning)

### ISSUE THREAD

**Issue by At0mn1yIvan** [At0mn1yIvan/unnmarkup#1]
**Tasks**:

- [x] Make chart on svg
- [x] Make accurate grid (by medical standarts)
- [x] Make the chart scroll along the X-axis
- [x] Work with scaling to keep the grid square
- [x] Add Legend to chart
- [ ] Make chart minimizing
