### ISSUE TITLE
Work with project structure, settings and includings

### ISSUE THREAD

**Issue by At0mn1yIvan** [At0mn1yIvan/unnmarkup#2]
**Tasks**:
- [x] Change static files for _markup_ app (add new directory in static)
- [x] Find out how to to connect a js file to html not via _base.html_
- [ ] Change the database to PostgreSQL
